### PR TITLE
initial functional mac app building

### PR DESCRIPTION
**Pull request by fprimex**
Whew, OK. As with many things like this, it took a very long time reading and researching but ultimately only a few lines of code. My savior here was an [issue filed with MuseScore](https://musescore.org/en/node/152151) where they dealt with this very problem.

The solution there was a lot more involved because that project is larger and more mature. After reading and trying many of the snippets of code I came to understand what was happening and did my own version.

This PR enables a clean build against master that produces a Mac `.app` bundle that actually works when transferred to a machine without any development libraries installed. The app should Just Work™. When I run it on my non-dev box it launches and I can run SM64 without any additional configuration.

TODO: The plugins and some other things are still being dumped in `Contents/MacOS` rather than a more suitable place like `Contents/Resources`. More commits coming, I suppose!

Here is the FS tree if anyone has feedback:

```
[mupen64plus-gui.app] $ tree
.
└── Contents
    ├── Frameworks
    │   ├── QtCore.framework
    │   │   ├── QtCore -> Versions/Current/QtCore
    │   │   ├── Resources -> Versions/Current/Resources
    │   │   └── Versions
    │   │       ├── 5
    │   │       │   ├── QtCore
    │   │       │   └── Resources
    │   │       │       └── Info.plist
    │   │       └── Current -> 5
    │   ├── QtGui.framework
    │   │   ├── QtGui -> Versions/Current/QtGui
    │   │   ├── Resources -> Versions/Current/Resources
    │   │   └── Versions
    │   │       ├── 5
    │   │       │   ├── QtGui
    │   │       │   └── Resources
    │   │       │       └── Info.plist
    │   │       └── Current -> 5
    │   ├── QtPrintSupport.framework
    │   │   ├── QtPrintSupport -> Versions/Current/QtPrintSupport
    │   │   ├── Resources -> Versions/Current/Resources
    │   │   └── Versions
    │   │       ├── 5
    │   │       │   ├── QtPrintSupport
    │   │       │   └── Resources
    │   │       │       └── Info.plist
    │   │       └── Current -> 5
    │   ├── QtWidgets.framework
    │   │   ├── QtWidgets -> Versions/Current/QtWidgets
    │   │   ├── Resources -> Versions/Current/Resources
    │   │   └── Versions
    │   │       ├── 5
    │   │       │   ├── QtWidgets
    │   │       │   └── Resources
    │   │       │       └── Info.plist
    │   │       └── Current -> 5
    │   ├── libSDL2-2.0.0.dylib
    │   ├── libfreetype.6.dylib
    │   ├── libpng16.16.dylib
    │   ├── libsamplerate.0.dylib
    │   └── libspeexdsp.1.dylib
    ├── Info.plist
    ├── MacOS
    │   ├── GLideN64.custom.ini
    │   ├── InputAutoCfg.ini
    │   ├── font.ttf
    │   ├── libmupen64plus.dylib
    │   ├── mupen64plus
    │   ├── mupen64plus-audio-sdl.dylib
    │   ├── mupen64plus-gui
    │   ├── mupen64plus-input-sdl.dylib
    │   ├── mupen64plus-rsp-cxd4-sse2.dylib
    │   ├── mupen64plus-video-GLideN64.dylib
    │   ├── mupen64plus.ini
    │   └── mupencheat.txt
    ├── PkgInfo
    ├── PlugIns
    │   ├── imageformats
    │   │   ├── libqgif.dylib
    │   │   ├── libqicns.dylib
    │   │   ├── libqico.dylib
    │   │   ├── libqjpeg.dylib
    │   │   ├── libqmacjp2.dylib
    │   │   ├── libqtga.dylib
    │   │   ├── libqtiff.dylib
    │   │   ├── libqwbmp.dylib
    │   │   └── libqwebp.dylib
    │   ├── platforms
    │   │   └── libqcocoa.dylib
    │   └── printsupport
    │       └── libcocoaprintersupport.dylib
    └── Resources
        ├── empty.lproj
        └── qt.conf

32 directories, 44 files
```

Lastly, the whole point here was distribution, so I've put up my build here:

https://1drv.ms/u/s!AjDZIIpQcHVngSwdHZ6N8nrq9ot6

`MD5 (mupen64plus-GLideN64-macos-201708-fprimex.zip) = 583f8c0b24791de59214735e8b80d819`

### CODE REVIEW

**Comment by loganmc10** [comment]
The only issue I have with this is that it puts everything inside "mupen64plus-gui.app'

mupen64plus-gui isn't the app, it is just one of the components. The user should also be able to launch mupen64plus (ui-console) if they choose. I don't know much about Mac architecture, but I don't see why you can't just distribute a regular folder with the various parts inside, just like is done on Linux and Windows

**Comment by fprimex** [comment]
Apologies for the length, but I wanted to be as definitive as possible in the options and my reasonings. We've never spoken or interacted in face to face to my knowledge, and I know tone is important in the emulation community. I am not super intense about this :) just trying to be helpful.

I see what you're saying but generally speaking what I've done is expected for the platform. It's a strange land, full of frameworks. End users expect an application to come with all of its dependencies. The app bundle is the vehicle all of that rides in. It can be moved around on the filesystem and will still work. The app bundle is kind of the mac equivalent of the directory that you are distributing, plus dep packaging/management for GUI programs.

It does not prevent the execution of command line programs from within the bundle if one is so inclined; the `DYLD_LIBRARY_PATH` just needs to be set to the `Frameworks` directory so the dependencies can be found:

```
$ pwd
/path/to/mupen64plus-gui.app/Contents/Frameworks
$ export DYLD_LIBRARY_PATH=$(pwd)
$ cd ../MacOS/
$ ./mupen64plus
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.5.0
...
```

M64PY is similar. Contents of the distributed DMG:

```
[/volumes/dmg] $ ls -1
AUTHORS
COPYING
ChangeLog
LICENSES
M64Py.app
README.md
mupen64plus.v64
```

And the app contains everything needed to run:

```
[M64Py.app] $ tree
.
└── Contents
    ├── Frameworks
    │   └── SDL2.framework
    │       ├── Headers
...  
    │       │   └── close_code.h
    │       ├── Resources
    │       │   └── Info.plist
    │       ├── SDL2
    │       └── Versions
    │           ├── A
    │           │   ├── Headers
...
    │           │   │   └── close_code.h
    │           │   ├── Resources
    │           │   │   └── Info.plist
    │           │   ├── SDL2
    │           │   └── _CodeSignature
    │           │       └── CodeResources
    │           └── Current
    │               ├── Headers
...
    │               │   └── close_code.h
    │               ├── Resources
    │               │   └── Info.plist
    │               ├── SDL2
    │               └── _CodeSignature
    │                   └── CodeResources
    ├── Info.plist
    ├── MacOS
    │   ├── PyQt5.Qt.so
... bunch more .so, .dylib, bin, sh, etc ...
    │   ├── libmupen64plus.dylib
...
    │   ├── m64py
    │   ├── m64py.sh
    │   ├── math.so
    │   ├── mupen64plus-audio-sdl.dylib
    │   ├── mupen64plus-input-sdl.dylib
    │   ├── mupen64plus-rsp-cxd4-sse2.dylib
    │   ├── mupen64plus-rsp-hle.dylib
    │   ├── mupen64plus-rsp-z64.dylib
    │   ├── mupen64plus-video-GLideN64.dylib
    │   ├── mupen64plus-video-arachnoid.dylib
    │   ├── mupen64plus-video-glide64mk2.dylib
    │   ├── mupen64plus-video-rice.dylib
    │   ├── mupen64plus-video-z64.dylib
    │   ├── pyexpat.so
    │   ├── pylzma.so
...
    │   └── zlib.so
    ├── Resources
    │   ├── GLideN64.custom.ini
    │   ├── GLideN64.ini
    │   ├── Glide64mk2.ini
    │   ├── InputAutoCfg.ini
    │   ├── RiceVideoLinux.ini
    │   ├── font.ttf
    │   ├── m64py.icns
    │   ├── mupen64plus.ini
    │   └── mupencheat.txt
    └── SharedSupport
...
        └── lgpl-license

22 directories, 306 files
```

There are, in general, a few choices for distribution:

1. Do what I've worked out already and distribute a complete app bundle with all deps that works with a double click. Command line works with one additional step, and a script could be included to set the needed environment variable and `exec` the binary to remove that step.

2. Don't package deps at all. Users will need to locate and install appropriate versions of the SDL, Qt, etc, libraries via brew or framework installs. There are many choices for how to accomplish this (frameworks from distributors/sites, brew, compile from source, etc), and not all versions of MacOS are going to support an easy installation of all of the particular dep versions. It's unreasonable IMO to expect Mac users to do this so that all installed deps are properly in the automatically available paths for both graphical and command line use. Qt in particular is not available for easy installation as a simple `dyld` vs a framework install. The Qt distribution and brew versions are both frameworks.

3. Package deps, but not in the app bundle. This has the same basic problem as running the UI at the command line in that `DYLD_LIBRARY_PATH` needs to be set. For the app, the graphical Qt deps will need to have their rpath rewritten to the Frameworks directory, while the command line deps (SDL) will need the rpath rewritten to point outside of the app bundle. If the app bundle is moved it will break, and if the libraries are moved or monkeyed with, since they're sitting out in plain view, everything will break.

4. Totally fight against the grain of the OS and try to dispense with an app bundle for the GUI entirely. I'm not sure if double clicking the binary would even work; it might have to be wrapped with a shell script with a specific `.command` extension to make it clickable. Right now `qmake` knows to make an app bundle just because it's running on a Mac. This option would require doing some platform-unusual things with `qmake` and Qt to get them to give you a "unix" type build on MacOS.

Of course you can do whatever you like :) You might consider soliciting feedback from other devs and Mac users to get more perspectives than just my own.

Cheers!

**Comment by loganmc10** [comment]
Hm ok I think you've convinced me :) is this ok to be merged then?

This week I'll try and get it configured in Travis CI so it'll produce automatic builds on m64p.github.io like it does for Linux and Windows

**Comment by fprimex** [comment]
Yeah I think this is ready. It works but the placement of things may not be the most optimal or proper inside the app bundle, but meh. I'll follow up with more testing in a bit. Let me know before you cut a release with a Mac build in case I end up with anything half finished, or found and not reported.

**Comment by clobber** [comment]
@fprimex Your script changes aren't quite right. First problem is it assumes the user has Qt5 installed via homebrew. The second problem is it assumes that if you installed Qt5 via homebrew that it lives in `/usr/local/Cellar/qt5` but on my install it is in `/usr/local/Cellar/qt`.

**Comment by clobber** [comment]
Also, there's no RSP plugins inside the app bundle (I guess they didn't get built and/or copied?) and the "Plugin and Path Selection" options make no sense.

The "Core Library Path" defaults to `./libmupen64plus.dylib` but that file/path doesn't even exist in the app bundle - it appears to be named just `mupen64plus` and is in `mupen64plus-gui/Contents/MacOS` - and the "Plugin Dir Path" defaults to just `./`. All these paths should be pre-set with the paths inside the app bundle with the best plugins chosen instead of defaulting to "dummy".

After setting the paths myself and compiling and copying in my own RSP plugin, I still cannot boot a game. I get the message: "Couldn't load core library, please set the path in settings."

**Comment by loganmc10** [comment]
It defaults to searching in the same directory as mupen64plus-gui, so that's why everything needs to be in the same folder.

> All these paths should be pre-set with the paths inside the app bundle with the best plugins chosen instead of defaulting to "dummy"

They are just set to dummy because it couldn't find the plugin folder, so it's all the same problem

**Comment by azoreseuropa** [comment]
Thanks, loganmc10..

We hope that someone can put instruction here for terminal to compile it.

**Comment by StenApp** [comment]
@fprimex 
Got it working too, lots of errors on MacOS 10.13...

The Mupen64Plus icon is missing in the app file.
Do you know a way to fix this?

**Pull request merged**
